Oras\PlaygroundBundle\Entity\Question:
    type: entity
    table: questions
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        questionType:
            type: smallint
            nullable: true
            unsigned: false
            comment: ''
            column: question_type
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
    manyToMany:
        set:
            targetEntity: Set
            cascade: {  }
            mappedBy: questions
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
